// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.15.8
// source: cost.proto

package cost

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CostClient is the client API for Cost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CostClient interface {
	GetUnitCost(ctx context.Context, in *CostRequest, opts ...grpc.CallOption) (*CostResponse, error)
	UpdateUnitCost(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	AddUnitCost(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	TotalBasket(ctx context.Context, in *Basket, opts ...grpc.CallOption) (*CostResponse, error)
}

type costClient struct {
	cc grpc.ClientConnInterface
}

func NewCostClient(cc grpc.ClientConnInterface) CostClient {
	return &costClient{cc}
}

func (c *costClient) GetUnitCost(ctx context.Context, in *CostRequest, opts ...grpc.CallOption) (*CostResponse, error) {
	out := new(CostResponse)
	err := c.cc.Invoke(ctx, "/Cost/GetUnitCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *costClient) UpdateUnitCost(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Cost/UpdateUnitCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *costClient) AddUnitCost(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/Cost/AddUnitCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *costClient) TotalBasket(ctx context.Context, in *Basket, opts ...grpc.CallOption) (*CostResponse, error) {
	out := new(CostResponse)
	err := c.cc.Invoke(ctx, "/Cost/TotalBasket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CostServer is the server API for Cost service.
// All implementations should embed UnimplementedCostServer
// for forward compatibility
type CostServer interface {
	GetUnitCost(context.Context, *CostRequest) (*CostResponse, error)
	UpdateUnitCost(context.Context, *UpdateRequest) (*UpdateResponse, error)
	AddUnitCost(context.Context, *UpdateRequest) (*UpdateResponse, error)
	TotalBasket(context.Context, *Basket) (*CostResponse, error)
}

// UnimplementedCostServer should be embedded to have forward compatible implementations.
type UnimplementedCostServer struct {
}

func (UnimplementedCostServer) GetUnitCost(context.Context, *CostRequest) (*CostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnitCost not implemented")
}
func (UnimplementedCostServer) UpdateUnitCost(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitCost not implemented")
}
func (UnimplementedCostServer) AddUnitCost(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUnitCost not implemented")
}
func (UnimplementedCostServer) TotalBasket(context.Context, *Basket) (*CostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalBasket not implemented")
}

// UnsafeCostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CostServer will
// result in compilation errors.
type UnsafeCostServer interface {
	mustEmbedUnimplementedCostServer()
}

func RegisterCostServer(s grpc.ServiceRegistrar, srv CostServer) {
	s.RegisterService(&Cost_ServiceDesc, srv)
}

func _Cost_GetUnitCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServer).GetUnitCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cost/GetUnitCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServer).GetUnitCost(ctx, req.(*CostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cost_UpdateUnitCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServer).UpdateUnitCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cost/UpdateUnitCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServer).UpdateUnitCost(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cost_AddUnitCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServer).AddUnitCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cost/AddUnitCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServer).AddUnitCost(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cost_TotalBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Basket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CostServer).TotalBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cost/TotalBasket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CostServer).TotalBasket(ctx, req.(*Basket))
	}
	return interceptor(ctx, in, info, handler)
}

// Cost_ServiceDesc is the grpc.ServiceDesc for Cost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cost",
	HandlerType: (*CostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnitCost",
			Handler:    _Cost_GetUnitCost_Handler,
		},
		{
			MethodName: "UpdateUnitCost",
			Handler:    _Cost_UpdateUnitCost_Handler,
		},
		{
			MethodName: "AddUnitCost",
			Handler:    _Cost_AddUnitCost_Handler,
		},
		{
			MethodName: "TotalBasket",
			Handler:    _Cost_TotalBasket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cost.proto",
}
